---
public_ip: 52.149.172.80
db_host: psqlflexibledb-prod.postgres.database.azure.com
db_user_name: postgres
db_name: postgres
db_pass: p@ssw0rd42
db_port: 5432
okta_url: https://dev-99529587.okta.com
okta_id: 0oa4hjrtkyTzMAVoI5d7
okta_secret: 1k0p3NvnLgwkP6Evy3sGIcIkmJCyOg5FmFAgXcIJ